version: '2.1'

x-logging:
  &default-logging
  options:
    max-file: '1'
    compress: 'false'
  driver: local

volumes:
    nginx_certs: {}
    nginx_vhost: {}
    nginx_html: {}
    nginx_acme: {}

networks:
  graphprotocol-mainnet-docker_monitor-net:
    external: true
  graphprotocol-testnet-docker_monitor-net:
    external: true

services:

######################################################################################
#####################             GNOSIS NODE                  #######################
######################################################################################

  gnosis-nethermind:
    hostname: gnosis-nethermind
    container_name: gnosis-nethermind
    image: nethermindeth/nethermind:db-traces
    command: [
      "--JsonRpc.EnabledModules=Eth,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc",
      "--JsonRpc.Enabled=true",
      "--JsonRpc.Port=8545",
      "--JsonRpc.Host=0.0.0.0",
      "--JsonRpc.EngineHost=0.0.0.0",
      "--JsonRpc.EnginePort=8551",
      "--JsonRpc.JwtSecretFile=/nethermind/jwtsecret/jwt.hex",
      "--Metrics.ExposePort=9090",
      "--config=xdai_archive",
      "--Sync.FastSync=false",
      "--TraceStore.Enabled=true",
      "--TraceStore.BlocksToKeep=0",
      "--TraceStore.TraceTypes=Trace,Rewards"
    ]
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - graphprotocol-mainnet-docker_monitor-net
      - graphprotocol-testnet-docker_monitor-net
    expose:
      - 30303
      - 9090
      - 8545
      - 8551
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
      - "8545:8545"
      - "8551:8551"
    volumes:
      - /home/root/gnosis/execution/nethermind_db:/nethermind/nethermind_db
      - /home/root/gnosis/execution/keystore:/nethermind/keystore
      - /home/root/gnosis/execution/logs:/nethermind/logs
      - /home/root/gnosis/jwtsecret:/nethermind/jwtsecret
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETHERMIND_METRICSCONFIG_ENABLED=true
    logging: *default-logging


######################################################################################
#####################             Teku NODE                  #########################
######################################################################################

  consensus:
    user: "${PUID:-0}"
    container_name: consensus
    image: consensys/teku:latest
    restart: always
    networks:
      - graphprotocol-mainnet-docker_monitor-net
      - graphprotocol-testnet-docker_monitor-net
    ports:
      - 9000:9000/tcp # p2p
      - 9000:9000/udp # p2p
      - 5054:5054/tcp # metrics
    expose:
      - 4000
    volumes:
      - /home/root/gnosis/consensus:/data
      - /home/root/gnosis/jwtsecret/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JAVA_OPTS=-Xmx4g
    command: |
      --network=gnosis
      --data-base-path=/data
      --data-storage-archive-frequency=2048
      --data-storage-mode=PRUNE
      --data-storage-non-canonical-blocks-enabled=false
      --log-destination=CONSOLE
      --logging=info
      --p2p-enabled=true
      --p2p-port=9000
      --p2p-peer-upper-bound=50
      --rest-api-enabled=true
      --rest-api-host-allowlist=*
      --rest-api-interface=0.0.0.0
      --rest-api-port=4000
      --rest-api-cors-origins=*
      --rest-api-docs-enabled=false
      --ee-endpoint=http://gnosis-nethermind:8551
      --ee-jwt-secret-file=/jwt.hex
      --eth1-deposit-contract-max-request-size=8000
      --metrics-enabled=true
      --metrics-host-allowlist=*
      --metrics-interface=0.0.0.0
      --metrics-port=5054
      --initial-state=https://checkpoint.gnosischain.com/eth/v2/debug/beacon/states/finalized
    logging: *default-logging


######################################################################################
#####################          NGINX PROXY CONTAINER           #######################
######################################################################################



  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    #environment:
    #  PROMETHEUS_HOST: ${PROMETHEUS_HOST}
    #  HTTP_AUTH_LOGIN: ${HTTP_AUTH_USER}
    #  HTTP_AUTH_PASSWORD: ${HTTP_AUTH_PASSWORD}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    #  - ./nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - ./graphprotocol-mainnet-docker/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - graphprotocol-mainnet-docker_monitor-net
      - graphprotocol-testnet-docker_monitor-net
    restart: unless-stopped
    logging: *default-logging


######################################################################################
#####################            NGINX SSL CONTAINER           #######################
######################################################################################


  nginx-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-ssl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_acme:/etc/acme.sh
    #  - ./nginx-proxy/htpasswd:/etc/nginx/htpasswd
      - ./graphprotocol-mainnet-docker/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - graphprotocol-mainnet-docker_monitor-net
      - graphprotocol-testnet-docker_monitor-net
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: ${EMAIL}
    logging: *default-logging


###https://docs.nethermind.io/nethermind/ethereum-client/configuration/metrics####
#Grafana-dashboard# https://github.com/NethermindEth/metrics-infrastructure/blob/master/grafana/dashboards/nethermind.json